[data]

[data.edlp]
type = "aixm"
source = "aixm/EDLP_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"

[data.edlp_layout]
type = "kml"
source = "kml/EDLP/layout.kml"

[profiles]

[profiles.TWR]
maps = [
    { map = "GRP-PHX", target = "EDGG/Plugins/GRP/Phoenix/GRpluginMaps.txt" },
    { map = "GRP-Stands", target = "EDGG/Plugins/GRP/Phoenix/GRpluginStands.txt" }
]
dir = "EDGG/Plugins/GRP/Phoenix/"
aliases = [ "PHX" ]

#[profiles.TWR_DAY]
#maps = [
#    { map = "settings-grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginSettings.txt" },
#    { map = "settings-topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkySettings.txt" },
#    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginMaps.txt" },
#    { map = "topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkyMaps.txt" },
#]
#dir = "Plugins/EDWW FIR beta/TWR_DAY/"
#aliases = [ "bright" ]

[runways]

[runways.EDLP.24]
thr = [ 51.619440, 8.629478 ]
bearing = 237
fap = [ 51.683997, 8.790263 ] # IBEGO
loc = [ 51.606375, 8.597428 ]

[runways.EDLP.06]
thr = [ 51.608713, 8.603167 ] 
bearing = 57
fap = [ 51.543349, 8.445633 ] # KOMIL
loc = [ 51.621207, 8.633786 ]


