[data]

[data.rawdata]
type = "raw"
source = "data"

[data.edlp]
type = "aixm"
source = "aixm/EDLP_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"

[data.edlp_layout]
type = "kml"
source = "kml/EDLP/layout.kml"

[data.edlw]
type = "aixm"
source = "aixm/EDLW_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"

[data.edlw_layout]
type = "kml"
source = "kml/EDLW/layout.kml"

[data.edln]
type = "aixm"
source = "aixm/EDLN_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"

[data.edln_layout]
type = "kml"
source = "kml/EDLN/layout.kml"

[profiles]

[profiles.Default]
maps = [
    { map = "GRP Phoenix Maps", target = "EDGG/Plugins/GRP/Phoenix/GRpluginMaps.txt" },
    { map = "GRP Stands", target = "EDGG/Plugins/GRP/Phoenix/GRpluginStands.txt" },
    { map = "TopSky EDUU Maps", target = "EDGG/Plugins/Topsky_EDUU/TopSkyMaps.txt" },
    { map = "TopSky EDGG Maps", target = "EDGG/Plugins/Topsky_EDGG/TopSkyMaps.txt" },
    { map = "TopSky EDYY Maps", target = "EDGG/Plugins/Topsky_EDYY/TopSkyMaps.txt" },
    { map = "TopSky Phoenix Maps", target = "EDGG/Plugins/Topsky_Phoenix/TopSkyMaps.txt" }
]
dir = "EDGG/Plugins/"
aliases = [ "Default" ]

#[profiles.TWR_DAY]
#maps = [
#    { map = "settings-grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginSettings.txt" },
#    { map = "settings-topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkySettings.txt" },
#    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginMaps.txt" },
#    { map = "topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkyMaps.txt" },
#]
#dir = "Plugins/EDWW FIR beta/TWR_DAY/"
#aliases = [ "bright" ]

[runways]

#-----------EDLP--------------

[runways.EDLP.24]
thr = [ 51.619440, 8.629478 ]
bearing = 237

[runways.EDLP.06]
thr = [ 51.608713, 8.603167 ] 
bearing = 57

#-----------EDLW--------------

[runways.EDLW.24]
thr = [ 51.522206, 7.623252 ]
bearing = 240
loc = [ 51.513317, 7.598003 ]

[runways.EDLW.06]
thr = [ 51.516019, 7.605664 ] 
bearing = 60
loc = [ 51.524903, 7.630898 ]

#-----------EDLN--------------

[runways.EDLN.31]
thr = [ 51.226991, 6.511213 ]
bearing = 308

[runways.EDLN.13]
thr = [ 51.233725, 6.497791 ] 
bearing = 128

#-----------EDDL--------------

[runways.EDDL.23L]
thr = [ 51.294278, 6.782787 ]
bearing = 233
loc = [ 51.277864, 6.748345 ]

[runways.EDDL.05R]
thr = [ 51.281248, 6.755424 ] 
bearing = 53
loc = [ 51.297669, 6.789874 ]

[runways.EDDL.23R]
thr = [ 51.296757, 6.776128 ]
bearing = 233
loc = [ 51.281945, 6.745040 ]

[runways.EDDL.05L]
thr = [ 51.285295, 6.752085 ] 
bearing = 53
loc = [ 51.300616, 6.784241 ]